# Generated by Django 5.2.3 on 2025-06-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvendor',
            name='business_name',
            field=models.CharField(default='default bname', max_length=100),
            preserve_default=False,
        ),
    ]
